nneaning/meaning_Server

modules/multer.js
package.json

multer를 사용하기 위한 사전 작업 수행,
- 필요 모듈 설치 목록
- multer
- multer-s3
- aws-sdk
- 미들웨어로 등록하기 위한 modules/multer.js 생성
- multer.js
```
const multer = require('multer');
const multerS3 = require('multer-s3');
const aws = require('aws-sdk');
aws.config.loadFromPath(__dirname + '/../config/s3.json');
const s3 = new aws.S3();
const upload = multer({
storage: multerS3({
s3,
bucket: 'sopt-27',
acl: 'public-read',
key: function (req, file, cb) {
cb(
null,
'images/origin/' +
Date.now() +
'.' +
file.originalname.split('.').pop(),
);
},
}),
});
module.exports = upload;
```
상기 multer.js를 모듈로 불러와 미들웨어로 사용
ex)
```
const upload = require('modules/multer.js');
router.post('/upload', upload.single('file'), async function(res, req) {
// body
});
```
2021.01.03
related to #9

[feat]: multer 사전 설정

---

modules/multer.js
package.json

s3의 버켓 위치가 잘못 잡혀있었습니다.
meaning을 위해 할당받은 s3의 스토리지로 파일이 업로드 되도록 설정값을 수정했습니다.
```
...(생략)...
const s3 = new aws.S3();
const upload = multer({
storage: multerS3({
s3,
bucket: 'sopt-27',
...(생략)...
```
```
...(생략)...
const s3 = new aws.S3();
const upload = multer({
storage: multerS3({
s3,
bucket: 'meaning-s3-bucket',  // modified
...(생략)...
```
2021.01.03
related to #9

[fix]: 잘못된 s3의 버켓 위치를 수정

---

controller/timeStampController.js

- 누락 파라미터에 대한 검증 로직이 부재한 점을 발견했습니다. 이에 해당 로직을 추가하고 다시 pull을 요청합니다.
- 요청 시 파라미터 누락에 대해 검사하는 과정 추가
> timeStampController.js
```
...(생략)...
if (!dateTime || !timeStampContents || !timeStampImageUrl) {
return res
.status(statusCode.BAD_REQUEST)
.send(
util.fail(
statusCode.BAD_REQUEST,
responseMessage.NULL_VALUE,
),
);
}
...(생략)...
```
2021-01-06
#9

[fix]: 타임스탬프 작성 요청시, 파라미터 누락 검증 로직 추가

---

controller/userController.js
modules/responseMessage.js
routes/users/index.js
service/userService.js

- 회원 가입 후, 온보드 상에서 등록할 정보(닉네임, 기상시간)을 서버에 등록하는 API를 구현하였습니다.
- PUT 메소드로 헤더, 바디를 필요로합니다. 명세서 참고를 부탁드립니다.
[API 명세서](https://github.com/nneaning/meaning_Server/wiki/%EC%98%A8%EB%B3%B4%EB%93%9C)
2021.01.07
#19

[feat] 온보드 정보 등록 요청 API

---

controller/groupController.js
controller/userController.js
models/group.js
models/index.js
models/post.js
modules/responseMessage.js
routes/group.js
routes/index.js
routes/users.js
service/groupService.js

- 그룹 생성 후, 그룹 테이블에 그룹 정보를 등록하고, 맴버 테이블에 유저를 등록하는 API를 구현했습니다.
- POST 메소드로 헤더, 바디를 필요로합니다. 명세서 참고를 부탁드립니다.
[API 명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EC%83%9D%EC%84%B1)
2021.01.07
#31

[feat]: 그룹생성 API 생성

---

controller/groupController.js
modules/responseMessage.js
routes/group.js
service/groupService.js

</br>
<div style="margin:0 auto;">
</div>
- 그룹 참가를 요청하는 API를 구현했습니다.
- 서비스 로직의 경우, 관리자(Host)로서 그룹에 참가시키는 API를 리팩토링하여 관리자, 일반 참가자 상관 없이 사용 할 수 있도록 하였습니다. [커밋 내역 확인하기](https://github.com/nneaning/meaning_Server/commit/cf0a3c6ac668b8a2a451cf6b05b2b1146f2a7c50)
- 헤더와 바디를 필요로합니다. 따라서 [명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EC%B0%B8%EA%B0%80-%EC%8B%A0%EC%B2%AD)를 참고 부탁드립니다.
2021-01-07
#35

[feat] 그룹 참가 API

---

controller/timeStampController.js
modules/responseMessage.js
service/postService.js

- 요청시,  body에 groupId를 키로 그룹의 id를 선택적으로 기입할 수 있습니다.
- 기입한 경우, 그룹의 피드로 타임스탬프를 포스팅합니다.
related to #9, #41
- 기존의 타임스탬프 작성 로직 위에 Post 객체 생성 로직을 추가하여, 그룹 피드에 타임스탬프 포스팅을 구현했습니다.
- [API 명세서](https://github.com/nneaning/meaning_Server/wiki/%ED%83%80%EC%9E%84%EC%8A%A4%ED%83%AC%ED%94%84-%EC%9E%91%EC%84%B1)
2021-01-08
#9, #41

[feat]: 타임스탬프 작성 API, 그룹 이용자용

---

controller/userController.js
models/todaysPromise.js
modules/dateTimeModule.js
modules/responseMessage.js
routes/user.js
service/postService.js
service/userService.js

[이슈](https://github.com/nneaning/meaning_Server/issues/46)
- 오늘 하루 다짐 데이터를 저장하는 API입니다. 
- todaysPromiseContents을 body값으로 받습니다.
- 미리 데이터를 넣고, GET방식으로 데이터를 제공할 땐, User에 연결하는 방식을 앞으로 고안해야합니다.
- URL과 헤더를 통해 파라미터를 받습니다. 명세서를 참고 부탁드립니다.
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EB%82%B4%EB%B6%80-%ED%94%BC%EB%93%9C)
2021-01-10
- #46 
- #47

[feat]: 오늘 하루 다짐 작성 및 제공 API

---

controller/userController.js
models/bookComment.js
modules/responseMessage.js
routes/user.js
service/postService.js
service/userService.js

[이슈](https://github.com/nneaning/meaning_Server/issues/50)
- 자기회고 및 일기를 작성하는 API입니다. 
- user의 id를 토큰에서 가져오고, body값으로 bookTitle, bookCommentContents를 받아서, 이를 DB에 저장합니다.
- URL과 헤더를 통해 파라미터를 받습니다. 명세서를 참고 부탁드립니다.
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EB%82%B4%EB%B6%80-%ED%94%BC%EB%93%9C)
2021-01-10
- #50

[feat]: 독후감 API 개발 추가

---

controller/userController.js
modules/responseMessage.js
routes/user.js
service/postService.js
service/userService.js

[이슈](https://github.com/nneaning/meaning_Server/issues/49)
- 자기회고 및 일기를 작성하는 API입니다. 
- user의 id를 토큰에서 가져오고, body값으로 diartContents를 받아서, 이를 DB에 저장합니다.
- URL과 헤더를 통해 파라미터를 받습니다. 명세서를 참고 부탁드립니다.
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EB%82%B4%EB%B6%80-%ED%94%BC%EB%93%9C)
2021-01-10
- #49

[feat]: 자기회고 및 일기 작성 API 추가

---

controller/groupController.js
controller/timeStampController.js
modules/dateTimeModule.js
modules/responseMessage.js
routes/group.js
service/groupService.js

- 그룹 설정 뷰에서 필요한 정보들을 제공합니다.
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EC%84%A4%EC%A0%95)
- 헤더로 토큰과, URL에 조회하고자 하는 그룹의 id를 받습니다.
- 요청 URL: /group/:groupId/edit
2021-01-10
#51

[feet] 그룹 설정 정보 제공 API

---

controller/groupController.js
controller/userController.js
modules/responseMessage.js
routes/group.js
routes/user.js
service/groupService.js
service/userService.js

[이슈](https://github.com/nneaning/meaning_Server/issues/24)
- 그룹의 상세정보를 제공하는 API입니다. 
- params값으로 groupId를 받고, 이 데이터를 활용해 그룹의 상세 정보를 제공합니다.
- URL과 헤더를 통해 파라미터를 받습니다. 명세서를 참고 부탁드립니다.
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EC%83%81%EC%84%B8%EB%B3%B4%EA%B8%B0)
- 2021-01-11
- #24

[feat]: 그룹리스트 상세보기 API

---

controller/userController.js

[이슈](https://github.com/nneaning/meaning_Server/issues/10)
- 로그인 API입니다. 
- 기존 로그인 로직에서 유저의 닉네임과 기상시간을 제공하는 로직으로 변경했습니다.
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EB%A1%9C%EA%B7%B8%EC%9D%B8)
- 2021-01-11
- #10

[fix]: 로그인 API 닉네임과 기상시간 제공하는 로직 추가

---

controller/groupController.js

- 그룹을 생성할 경우, 응답 바디에 그룹Id를 첨부합니다.
- related to #31 
ex
```
{
"status": 201,
"success": true,
"message": "그룹 생성 완료"
}
```
```
{
"status": 201,
"success": true,
"message": "그룹 생성 완료",
"data": {
"groupId": 43
}
}
```
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EC%83%9D%EC%84%B1)
2021-01-11
#31

[feat]: 그룹 생성시 생성된 그룹의 id 응답

---

controller/userController.js
modules/responseMessage.js

- 일기 작성 시 하루 다짐 레이어의 응답 메세지가 첨부되는 것을 수정했습니다.
- 내용의 중복을 검사하는 로직이 있었습니다. 일기는 내용이 중복되어도 상관 없기에 삭제했습니다.
2021-01-11
related to #49

[fix]: 일기 작성 API 응답 문구 변경 및 내용 검증 로직 삭제

---

modules/dateTimeModule.js

- 원인은 알 수 없으나, 정규표현식의 검증 메소드(:regularExpressionObejct.test(String))가 불안정한 현상이 있었습니다.
- 제대로 된 시간 포맷 'HH:mm:ss'를 맞추어 보내도, 불규칙적으로 검증을 통과하거나 그러지 못하는 현상이 반복되었습니다.
- 따라서 검증시 dayjs 라이브러리를 사용하도록 대체합니다.
```
checkValidTimeFormat: (timeString) =>
timeFormatRegularExpression.test(timeString),
```
```
function checkValidTimeFormat(timeString) {
const tempDateTime = `${dayjs().format(FORMAT_DATE)} ${timeString}`;
return dayjs(tempDateTime, FORMAT_DATETIME, true).isValid();
}
```
2021-01-12

[fix]: 온보드 등록시 시간 포맷 검증에서의 불안정성 해결

---

routes/group.js

- 그룹 내부 피드 화면의 API 요청 URL이 명세서와 다르게 설정되어 있어, 수정합니다.
related to #43
- 요청 url: group/:groupId/post?offset=:offset
- 요청 url: group/:groupId/feed?offset=:offset
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EB%82%B4%EB%B6%80-%ED%94%BC%EB%93%9C)
2021-01-12
#43

[refactor]: 그룹 내부 피드 API 요청 URL 변경

---

controller/groupController.js
controller/userController.js
modules/responseMessage.js
routes/group.js
routes/user.js
service/userService.js

- 사용자 계정의 온보드 정보를 삭제합니다.
- DB의 해당 값을 null로 채워넣습니다.
- 개발 과정에서 생산성을 높이기 위해 구현하였습니다.
- [명세서](https://github.com/nneaning/meaning_Server/wiki/%EC%98%A8%EB%B3%B4%EB%93%9C-%EC%82%AD%EC%A0%9C)
2021-01-12
#69

[feat] 온보드 정보 초기화(삭제)

---

controller/timeStampController.js

- missionStatus가 misstionStatus로 표기되는 오타가 있어 수정합니다.
```
const dto = {
timeStampId: timeStamp.id,
misstionStatus: timeStampMissionStatus,
};
```
```
const dto = {
timeStampId: timeStamp.id,
missionStatus: timeStampMissionStatus,
};
```
2021-01-13

[fix]: 타임스탬프 작성 API 응답 오타 수정

---

controller/groupController.js
modules/responseMessage.js
routes/group.js

- 토큰을 받아 유저가 가입되어있는 그룹의 정보를 응답합니다.
- 가입된 그룹이 없는 경우 null을 리턴합니다.
related to #79
[명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B0%80%EC%9E%85-%EA%B7%B8%EB%A3%B9-%EC%A1%B0%ED%9A%8C)
2021-01-13
#79

[feat]: 사용자가 가입된 그룹 정보 요청

---

controller/groupController.js
modules/responseMessage.js

- [이용자가 속한 그룹을 조회하는 API](https://github.com/nneaning/meaning_Server/wiki/%EA%B0%80%EC%9E%85-%EA%B7%B8%EB%A3%B9-%EC%A1%B0%ED%9A%8C)가 만들어짐에 따라, 대체 될 수 있는 만큼을 삭제했습니다.
더 이상 요청 이용자가 가입된 그룹의 정보를 그룹 리스트 조회 API에서 응답하지 않습니다.
[명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EB%A6%AC%EC%8A%A4%ED%8A%B8)
2021-01-14
related to #23

[refactor]: 그룹리스트 조회 API가 더 이상 myGroup을 포함하지 않음

---

controller/groupController.js

- 해당 뷰에서 필요한 데이터(그룹 생성일)이 누락되어 수정합니다.
```
const {
groupName,
introduction,
maximumMemberNumber,
} = await groupService.readGroup(groupId);
if (!groupName || !introduction || !maximumMemberNumber) {
return res
.status(statusCode.BAD_REQUEST)
.send(util.fail(statusCode.BAD_REQUEST, responseMessage.NO_SUCH_GROUP));
}
const group = {
groupId,
groupName,
introduction,
maximumMemberNumber,
};
```
```
const {
groupName,
introduction,
maximumMemberNumber,
createdAt,
} = await groupService.readGroup(groupId);
if (!groupName || !introduction || !maximumMemberNumber || !createdAt) {
return res
.status(statusCode.BAD_REQUEST)
.send(util.fail(statusCode.BAD_REQUEST, responseMessage.NO_SUCH_GROUP));
}
const group = {
groupId,
groupName,
introduction,
maximumMemberNumber,
createdAt,
};
``` …

[fix]: 그룹 설정 정보 응답에 그룹 생성일 포함하여 응답

---

controller/userController.js
modules/encryptModule.js
service/userService.js

다음과 같은 문제가 발생하였습니다.
1. 잘못된 비밀번호로 로그인 하였을 때 클라이언트 측에서는 응답코드 400과 함께 '로그인 실패'라는 메세지를 받았습니다. 잘못된 비밀번호를 입력한 경우, '비밀번호가 일치하지 않습니다.'라는 메세지가 수신되기를 예상하며 그러한 코드도 작성되어 있으나, 작동하지 않았습니다.
2. 서버측의 로그에는 HTTP Status Code 500으로 기록됩니다. 이러한 현상이 발생한 이유는,
- 잘못된 비밀번호를 암호화하여 DB를 탐색하기 때문에 리턴되는 계정 정보가 없음
- 따라서 null이 반환되는데, null에서 password 필드를 읽어오려 함
- 내부적으로 예외가 발생하고, 이는 예외 처리문에 의해 처리됨
- 그러나 예외처리문에서는 상태코드 500이 아닌 400으로 응답
따라서, 이와 같은 문제를 해결하고, 예상치 못한 예외가 발생한 경우 500으로 응답하도록 수정하였습니다.
[명세서](https://github.com/nneaning/meaning_Server/wiki/%EB%A1%9C%EA%B7%B8%EC%9D%B8)
2021-01-14

[fix]: 잘못된 비밀번호로 로그인을 시도했을 때 응답 메세지가 제대로 송신되지 않는 문제 해결

---

controller/groupController.js
modules/responseMessage.js
service/groupService.js

- 그룹 생성 시 DB에서 이미 해당 그룹명을 가지고 있는지 검사하는 로직을 추가했습니다.
- 또한 요청 거부시 서버 내부 오류를 제외하고 모두 Status Code 400으로 응답하는 것을 수정했습니다.
[명세서](https://github.com/nneaning/meaning_Server/wiki/%EA%B7%B8%EB%A3%B9-%EC%83%9D%EC%84%B1)
2021-01-14
#31

[fix]: 그룹 생성 시 그룹명 중복 검사 및 응답 코드 구분화

---

controller/groupController.js

- 그룹의 id값에서 미리 저장해둔 그룹이미지의 갯수를 나누고, 나눈 값을 그룹이미지의 id로 받는 과정에서,
- id가 0으로 받아져서 이미지가 모두 저장되지 않은 버그 수정
- 2021-01-14
- #31

[fix]: 그룹생성 API에서 groupImage를 제공받지 못한 에러 해결

---

controller/groupController.js
service/groupService.js

- 그룹의 id값에서 미리 저장해둔 그룹이미지의 갯수를 나누고, 나눈 값을 그룹이미지의 id로 받는 과정에서,
- id가 0으로 받아져서 이미지가 모두 저장되지 않은 버그 수정
- 변수명의 중복으로 인해 생긴 문제라고 판단.
- 2021-01-15
- #31

[fix]: 그룹생성 API에서 그룹 생성 시, 그룹 이미지가 생성되지 않은 에러 해결
